### ISSUE TITLE
L5R

### ISSUE THREAD

**Issue by wargamesqcf** [BrowncoatShadow/rpg-sheet#2]
is it possible to add a Legend of the five rings rpg sheet to this?
https://www.l5r.com/files/2012/04/L5R-4E-Character-Sheet-LoRes.pdf

**Comment by hanatokitsu** [comment]
Absolutely. It will require some work, but if you know HTML and CSS, you can do it. The 5th Edition sheet is a good example to start with, as it takes advantage of everything currently implemented.

Here are a few key concepts that will help in understanding how sheets work:
- Everything is client-side HTML, CSS, and JavaScript. It is a very simple model that currently does not do anything fancy like auto-calculation for stats. Think of it like a virtual version of a pen and paper character sheet.
- A sheet is an HTML form displayed over images of your character sheet pages. SVGs work best, because zooming.
- Fields on the sheet are named inputs (fields, textareas, checkboxes) for the form, that are sized and positioned relative to the page with CSS. This is the most labor intensive part of the process.
- The character sheet is saved by serializing the form into a JSON object using the model defined by the names of the fields. This functionality is handled by the app, but the fields have to be named properly using a `bracketed[object][syntax]`.
- They are loaded back in by deserializing that data back into the input fields.
- The forms also have some hidden fields that act as meta-data so character sheet files can know what sheet to load when being imported back in. You can also give a particular field `id="filename"` which tells the app to use text in that input to save the filename.

It is probably not the most efficient way to map data on the page, but it was a proof-of-concept that worked. If you need more help building a sheet, you can find me on freenode as `BrowncoatShadow`. Send me a message and I can walk you through with more detail.
